apiVersion: batch/v1
kind: CronJob
metadata:
  name: drift-check-cron
spec:
  schedule: "0 * * * *"   # 매 시간마다 실행
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: drift-check
            image: curlimages/curl:latest
            args:
              - curl
              - "-X"
              - "GET"
              - "http://fastapi-service.default.svc.cluster.local:8000/api/check_drift/?period=1%20hour&event_name=실시간%20인식&threshold=0.3"
          restartPolicy: OnFailure
